---
- name: Setup Yolo on Ubuntu Server 22.04
  hosts: all
  become: true
  remote_user: root
  roles:
    - server-configuration
    - docker-install
    - clone-yolo
    - common
    - backend
    - client