---
  - name: Clone Yolo from GitHub
    git:
      repo: https://github.com/The-Algorist/yolo.git
      dest: /opt/yolo
  - name: Initialize Yolo containers
    docker_compose:
      state: present
      project_src: /opt/yolo
      compose_files:
        - "{{ lookup('file', 'docker-compose.yaml') }}"
