---
  - name: Clone Yolo from GitHub
    git:
      repo: https://github.com/The-Algorist/yolo.git
      dest: /opt/yolo

  - name: Find the path to the docker-compose.yaml file
    set_fact:
      docker_compose_file_path: "{{ lookup('file', '/opt/yolo/docker-compose.yaml') }}"

  - name: Initialize Yolo containers
    docker_compose:
      state: present
      project_src: /opt/yolo
      compose_files:
        - "{{ lookup('file', 'docker-compose.yaml') }}"
