---
apiVersion: v1
kind: Service
metadata:
  name: client-service
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer